### ISSUE TITLE
Error reading breakpoint csv file create_duration_data replacement has 1 row, data has 0

### ISSUE THREAD

**Issue by akrherz** [ryanpmcg/WEPPCLIFF#19] opened 2020-10-21 19:29 UTC
My environment is R 3.6.3, WEPPCLIFF (current github master), RedHat Linux 8 x64.  Am a providing the attached test.csv file (placed within the INPUT folder) containing a conversion of a breakpoint CLI file I have.  I run the following command (full details below) and get the following error

```
$  /opt/R-3.6.3/bin/Rscript --vanilla WEPPCLIFF.R --args -f test.csv  -la y -verb t -qc t
 Analyzing data intervals...Error in `$<-.data.frame`(`*tmp*`, "DUR", value = NA_real_) : 
  replacement has 1 row, data has 0
Calls: main ... core_workflow -> create_duration_data -> $<- -> $<-.data.frame
```

I can't decipher what I may have wrong with my CSV file.  Thank you.

<details>

```
$ /opt/R-3.6.3/bin/Rscript --vanilla WEPPCLIFF.R --args -f test.csv  -la y -verb t -qc t

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

________________________________________________________________________________
________________________________________________________________________________

 ___      ___ _______ _______  _______  _______ ___     _______ _______ _______
 | |  __  | | |  ___/ |  __  | |  __  | |  ___/ | |     |__ __| |  ___/ |  ___/
 | | /  \ | | | |___  | |__| | | |__| | | |     | |       | |   | |___  | |___
 | |/ /\ \| | |  __/  |  ____| |  ____| | |     | |       | |   |  __/  |  __/
 \   /  \   / | |___  | |      | |      | |___  | |___   _| |_  | |     | |
  \_/    \_/  |_____| |_|      |_|      |_____| |_____| |_____| |_|     |_|

________________________________________________________________________________
________________________________________________________________________________


  WEPP Climate File Formatter (WEPPCLIFF) Version 1.5
  Copyright (c) 2020 Ryan P. McGehee

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation (GNU GPL v3.0).

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  
  Please provide an appropriate citation in any published work as follows:

  McGehee, R.P., D.C. Flanagan, and P. Srivastava. 2020. WEPPCLIFF:
      A command-line tool to process climate inputs for soil loss models.
      Journal of Open Source Software. https://doi.org/10.21105/joss.02029
      Repository available at: https://github.com/ryanpmcg/WEPPCLIFF

  Corresponding Author: R.P. McGehee
  E-mail: ryanpmcgehee@gmail.com

 
******************************************************************************** 
 
 User Specified Arguments: 4 of 55 possible arguments. 
 
******************************************************************************** 

 
            INSTALLATION ARGUMENTS 

  First Run ----------------------------- fr :	  
  License Agreement --------------------- la :	 y 
 
  ******************************************** 
 
            INPUT/OUTPUT ARGUMENTS 

  Input Directory ------------------------ d :	  
  Output Directory ----------------------- o :	  
  Export Directory ----------------------- e :	  
  Plot Directory ------------------------- p :	  
  Library Directory ---------------------- l :	  
  Input Filename ------------------------- f :	 test.csv 
  Output Filename ----------------------- fn :	  
  File Delimiter --------------------- delim :	  
 
  ******************************************** 
 
            FUNCTIONALITY ARGUMENTS 

  Unit Conversion ------------------------ u :	  
  Quality Check ------------------------- qc :	 t 
  Impute Missing Data ------------------- id :	  
  Plot Data ----------------------------- pd :	  
  Export Data --------------------------- ed :	  
  Use Alternative Data ----------------- alt :	  
  Preserve Missing Data ---------------- pmd :	  
 
  ******************************************** 
 
            PRECIPITATION ARGUMENTS 

  Cumulative Precipitation -------------- cp :	  
  Precipitation Interval ---------------- pi :	  
  Calculate Erosion Indices ------------- ei :	  
  Energy Equation(s) -------------------- ee :	  
  Export Breakpoints -------------------- eb :	  
 
  ******************************************** 
 
            STORM CONTROL ARGUMENTS 

  Storm Identifier --------------------- sid :	  
  Storm Separation Time Threshhold ----- tth :	  
  Storm Separation Depth Threshhold ---- dth :	  
 
  ******************************************** 
 
           QUALITY CONTROL ARGUMENTS 

  Quality Checking Option ------------- qcop :	  
  Checking Threshold ----------------- chkth :	  
  Spiking Threshold ------------------ spkth :	  
  Streaking Threshold ---------------- strth :	  
  Sticking Threshold ----------------- stkth :	  
  Return Period ------------------------- rp :	  
 
  ******************************************** 
 
           IMPUTE CONTROL ARGUMENTS 

  Impute Method ------------------------- im :	  
  Iteration Override -------------------- io :	  
  Quick Impute -------------------------- qi :	  
  Impute Verbosity ---------------------- iv :	  
 
  ******************************************** 
 
          DATETIME CONTROL ARGUMENTS 

  Time Zone ----------------------------- tz :	  
  Start Datetime ----------------------- sdt :	  
  End Datetime ------------------------- edt :	  
  Round Time Bounds -------------------- rtb :	  
  Ignore Precipitation Bounds ---------- ipb :	  
  Precipitation Datetime Format ------- dtf1 :	  
  Alternative Data Datetime Format ---- dtf2 :	  
  Non-Precipitation Datetime Format --- dtf3 :	  
 
  ******************************************** 
 
         CLIGEN FILE FORMAT ARGUMENTS 

  CLIGEN Version ------------------------ cv :	  
  Simulation Mode ----------------------- sm :	  
  Breakpoint Format --------------------- bf :	  
  Wind Information ---------------------- wi :	  
 
  ******************************************** 
 
            OPTIMIZATION ARGUMENTS 

  Multiprocessing ----------------------- mp :	  
 
  ******************************************** 
 
              DEVELOPER ARGUMENTS 

  Profile Code ------------------------ prof :	  
  Profile Interval -------------------- pint :	  
  Profile Memory ---------------------- mepr :	  
  Profile Garbage Collection ---------- gcpr :	  
  Profile Lines ----------------------- lnpr :	  
  Show Warnings ----------------------- warn :	  
  Verbosity --------------------------- verb :	 t 
 
 
******************************************************************************** 

 
Loading R package dependencies... Completed in 0.495 seconds. 
 
Detected 1 station. Parallel processing has been disabled. 
 
Processing station... 
 Loading input file... 
 Preprocessing data... 
 Storing in memory...
 Converting data format...
 Analyzing data intervals...Error in `$<-.data.frame`(`*tmp*`, "DUR", value = NA_real_) : 
  replacement has 1 row, data has 0
Calls: main ... core_workflow -> create_duration_data -> $<- -> $<-.data.frame
In addition: Warning messages:
1: In dir.create(var) :
  '/home/akrherz/projects/WEPPCLIFF/LIBRARY' already exists
2: In dir.create(var) :
  '/home/akrherz/projects/WEPPCLIFF/INPUT' already exists
3: In dir.create(var) :
  '/home/akrherz/projects/WEPPCLIFF/OUTPUT' already exists
4: In dir.create(var) :
  '/home/akrherz/projects/WEPPCLIFF/EXPORT' already exists
5: In dir.create(var) :
  '/home/akrherz/projects/WEPPCLIFF/PLOTS' already exists
Timing stopped at: 0.327 0.002 0.33
Timing stopped at: 0.882 0.037 0.921
Execution halted
```
</details>

[test.zip](https://github.com/ryanpmcg/WEPPCLIFF/files/5418315/test.zip)

**Comment by ryanpmcg** [comment] 2020-10-22 00:34
@akrherz you just did not specify the datetime format. If you use Excel or another program to edit the .csv file, they quietly change the format to an Excel format upon saving and closing the file. Open it with a text editor to see that, and confirm it. 

There are two options to work around:
1. before saving and closing the Excel file, use custom format and specify the date time in the default R format
2. specify the date time format in the WEPPCLIFF command with -dtf1, -dtf2, -dtf3, see the [manual](https://github.com/ryanpmcg/WEPPCLIFF/blob/master/Manual.md) for how to use these.

For example, the excel format entry would be: -dtf1 "%m/%d/%y %H:%M"
Note the double quotes around an argument with a space.

**Comment by akrherz** [comment] 2020-10-22 01:15
Thanks for the response, if the datetime format does not match, shouldn't the error state as such?  Based on your suggestion, I still see the same error.  The datetime format I used under software control matches the default.

```
$ head -2 INPUT/test.csv
DT_1,PRECIP,DT_3,MAX_TEMP,MIN_TEMP,SO_RAD,W_VEL,W_DIR,DP_TEMP,STATION,LAT,LON,ELEV
2007-01-13 00:00:00,0.0,2007-01-01 00:00:00,1.7,-4.4,233,4.3,0,-5.0,test,42.4,-93.9,341

$ /opt/R-3.6.3/bin/Rscript --vanilla WEPPCLIFF.R --args -f test.csv  -la y -verb t -qc t -dtf1 "%Y-%m-%d %H:%M:%S" -dtf3 "%Y-%m-%d %H:%M:%S"
 Analyzing data intervals...Error in `$<-.data.frame`(`*tmp*`, "DUR", value = NA_real_) : 
  replacement has 1 row, data has 0
Calls: main ... core_workflow -> create_duration_data -> $<- -> $<-.data.frame
```

what's more puzzling is what the test suite uses, for example
```
Rscript --vanilla WEPPCLIFF.R --args -o $DIRECTORY/OUTPUT -e $DIRECTORY/OUTPUT -fn AutoTest.1 -f ASOS_BPT_KMQE.csv -la y -verb t -ed 1

$ head -2 INPUT/ASOS_BPT_KMQE.csv
DT_1,PRECIP,DT_3,MAX_TEMP,MIN_TEMP,SO_RAD,W_VEL,W_DIR,DP_TEMP,STATION,LAT,LON,ELEV
2000-01-02T10:50:00Z,0,2000-1-1 00:00:00,7.592592593,-3.62037037,97.76272671,7.055616272,223.7763889,-3.260889492,KMQE,42.21667,-71.116667,199
```

In that case, `ASOS_BPT_KMQE.csv` `DT_1` is iso9660ish and it can be read without any `dtf1` options.

**Comment by ryanpmcg** [comment] 2020-10-22 02:20
There are a number of things that particular error could have been from, but it would take too much time for me to design something to parse out which was the cause. 99% of the time, that error arises due to date time issues, which may or may not have to do with the dtf arguments. I can't see anything wrong based on what I see here, but I have not yet tried to run your example. Before I do that, will you let me know if you have run the auto test script yet? That will run a variety of commands that will test your installation and let me know if your machine has any incompatibilities. If not, please do when it is convenient, it takes less than 5 minutes to run on most machines.

**Comment by akrherz** [comment] 2020-10-22 02:29
> Before I do that, will you let me know if you have run the auto test script yet?

Indeed, I ran that as a part of the installation procedure, I did have to patch it as `md5sum` is the checksum command on my system.
 
```
  CONGRATULATIONS! Your WEPPCLIFF installation was successfully verified by 8
  automated test runs of 8 highly unique file outputs. Now you are ready to
  use WEPPCLIFF with peace of mind, knowing everything is working as intended.
```

**Comment by ryanpmcg** [comment] 2020-10-22 02:38
Ok, great! I will make a note for future users in the next version. I will run your example and get back to you soon. I will queue it to run after two experiments already running on my system.

**Comment by akrherz** [comment] 2020-10-22 03:03
I found the issue, `dt_3=2007-01-01 00:00:00` fails, `dt_3=2007-1-1 00:00:00` works :)  No idea why yet!

**Comment by ryanpmcg** [comment] 2020-10-22 03:18
I am not sure why that was an issue for you. I have used that date time format literally for thousands of files. FYI, when I ran your file using the Excel format after editing it in Excel, it worked fine.

**Comment by ryanpmcg** [comment] 2020-10-22 03:21
Let me know if there is anything else I can do to help.

**Comment by akrherz** [comment] 2020-10-22 03:46
More debugging

Example DT_3 value | read_csv type | R repr | Resulting DT_3 frame variable datatype
--- | -- | --- | --
2007-01-01 00:00:00 | double | 2007-01-01 | double
2007-1-1 00:00:00 | character | 2007-1-1 00:00:00 | integer

So `read_csv` is doing the conversion [automatically](https://readr.tidyverse.org/articles/readr.html#datetimes).  This patch appears to workaround this issue

```
$ git diff WEPPCLIFF.R 
diff --git a/WEPPCLIFF.R b/WEPPCLIFF.R
index b530c4a..7e3109f 100644
--- a/WEPPCLIFF.R
+++ b/WEPPCLIFF.R
@@ -308,7 +308,7 @@ load_input_file = function(f) {
     if (toupper(verb) == "T") {cat(lr, "Loading input file... ")}
     if (length(txt) == 1){file = suppressMessages(read_table(f, delim))}
     if (length(tsv) == 1){file = suppressMessages(read_tsv(f))}
-    if (length(csv) == 1){file = suppressMessages(read_csv(f))}})
+    if (length(csv) == 1){file = suppressMessages(read_csv(f, col_types=cols(DT_1="c", DT_3="c")))}})
   
   setwd(home.dir)
   return(file)}
```

**Comment by ryanpmcg** [comment] 2020-10-23 15:12
Thanks for the contribution @akrherz, I will do some testing with that to make sure it works in many cases and include it in the next version.

**Comment by HiroyukiYamadaGTUT** [comment] 2022-03-01 07:45
My "test_2.csv" in the attachment gives the same error. 

By the way, I tried @akrherz 's "test.csv" file and was able to generate the cli file without error.

In the tutorial, I got the same error when I ran the below code.

 `Rscript --vanilla WEPPCLIFF.R --args -f AH537_BPT_CP.csv -cp t -u m PRECIP -sm 2 -la y -ipb t`

I tried changing the format of the date and time in the file, but that didn't help. Could you please check my file?

```
C:\WEPPCLIFF>Rscript --vanilla WEPPCLIFF.R --args -f test_2.csv
↓
Processing station... ...Error in `$<-.data.frame`(`*tmp*`, "DUR", value = NA_real_) : 
  replacement has 1 row, data has 0
Calls: main ... core_workflow -> create_duration_data -> $<- -> $<-.data.frame
In addition: Warning messages: `
The following named parsers don't match the column names: DT_2
Timing stopped at: 0.47 0.04 0.43
Timing stopped at: 1.25 0.25 1.45
 Execution halted
```

[test_2.csv](https://github.com/ryanpmcg/WEPPCLIFF/files/8159671/test_2.csv)

**Comment by ryanpmcg** [comment] 2022-03-01 14:31
FYI, @HiroyukiYamadaGTUT, if you want to mention akrherz without sending him a notification, exclude the '@' from the name. akrherz is quite busy, and you probably want to notify him only if you actually need him to respond.

For your issue, open your test_2.csv file with notepad or another text editor to see the format of the datetime columns. Your file is in the format "%Y/%m/%d %H:%M" which is not the same as the WEPPCLIFF default "%Y-%m-%d %H:%M:%S". Either change the file format for datetime columns or change the -dtf options (-dtf1, -dtf2, and -dtf3) in your WEPPCLIFF command. The format code I provided above would work with your file. By default -dtf3 is set by -dtf1; you only specify it when DT_3 is different from DT_1. Thus, you only need to change -dtf1.

**Comment by HiroyukiYamadaGTUT** [comment] 2022-03-02 00:07
Thank you for letting me know about the notification feature. I'm sorry for the disturbance, akrherz .

Also, my issue has been solved.
I've solved my problem by changing the symbol between the year, month, and date to "-" instead of "/" and adding ":％s".
Thank you very much for your reply.

**Comment by akrherz** [comment] 2022-03-02 02:46
> I'm sorry for the disturbance, akrherz .

No problem at all, I am glad you got it working!

**Comment by ryanpmcg** [comment] 2022-03-03 16:05
I also forgot to close this issue since I made the appropriate edits to WEPPCLIFF. Now all files have the "DT_n" columns specified as character types.

**Closed as completed by ryanpmcg** 2022-03-03 16:05 UTC
